FROM python:3.9-slim
# ENV PYTHONPATH="./code/"

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    software-properties-common \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY . .
ENV PYTHONUNBUFFERED=1
RUN pip3 install -r requirements.txt

EXPOSE 8000


ENTRYPOINT ["streamlit", "run", "./ui/main.py", "--server.port=8000", "--server.address=0.0.0.0", "--server.enableXsrfProtection", "false"]