FROM python:3.10-slim

# Step 1 - Install dependencies
WORKDIR /app

# Step 2 - Copy only requirements.txt
COPY requirements.txt /app

# Install system dependencies
# Combine update, install, and cleanup steps to minimize image layers and reduce size
RUN apt-get update && apt-get install -y \
    graphviz \
    libgraphviz-dev \
    tk-dev \
    libffi-dev \
    git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*  # Clean up to reduce image size

# Step 4 - Install pip dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Step 5 - Copy the rest of the files
COPY . .
ENV PYTHONUNBUFFERED=1

# Expose the application port
EXPOSE 80

# do not change the arguments
CMD ["chainlit", "run", "./chat.py",  "--port=80"]